# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, default='default_picture.jpg', upload_to='')),
                ('about', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('authors', models.ManyToManyField(related_name='books', to='shop.Author')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
