# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter a valid phone number.', 'invalid')]),
        ),
    ]
